version: '3.8'

services:
  backend:
    build: ./gigflow/backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://gigflowadmin:gigflow123@gigflow.pbdkgj6.mongodb.net/gigflow?retryWrites=true&w=majority&appName=gigflow
      - JWT_SECRET=gigflow_super_secret_key_2026
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
      - FRONTEND_URL=http://frontend:80
    restart: unless-stopped

  frontend:
    build: ./gigflow/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
